name: CI

# We can specify what Github events trigger the action
on: push

jobs:
  build:
    # we can specify the OS
    runs-on: ubuntu-latest

    # a job is a series of steps
    steps:
      - name: Checkout repository
        uses: actions/Checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-Python@v5
        with:
          python-version: "3.11"

      - name: Install Python dependancies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt

      - name: Test with PyTest
        run: |
          python -m pytest --cov=inflammation.models tests/test_models.py